_partial_: true
num_workers: 8
collation_strategy: "sequence_classification"
_target_: bmfm_targets.training.data_module.DataModule
batch_size: 20
max_length: 512
shuffle: true
sequence_order: "random"
mlm: false
