  _target_: bmfm_targets.config.SCNystromformerConfig
  _partial_: true
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_act: gelu_new
  hidden_size: 768
  hidden_dropout_prob: 0.15
  attention_probs_dropout_prob: 0.1
  initializer_range: 0.02
  layer_norm_eps: 1.0e-05
  type_vocab_size: 2
  num_landmarks: 512 #128 # 64
  conv_kernel_size: 65
  inv_coeff_init_option: false
  pad_token_id: 1
  bos_token_id: 0
  eos_token_id: 2
  checkpoint: null
